services:
  - type: web
    name: multilingual-chatbot
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
    healthCheckPath: /
